### ISSUE TITLE
G-Sync will support HDMI VRR & Adaptive-Sync as basis for AMD FreeSync 

### ISSUE THREAD

**Issue by CHEF-KOCH** [CHEF-KOCH/nVidia-modded-Inf#10]
## Overview
Since this year users can use Nvidia G-Sync with some FreeSync monitors. But vice versa is (currently) not possible, this will be [changed now](https://www.tftcentral.co.uk/blog/nvidia-open-up-support-for-adaptive-sync-freesync-for-future-native-g-sync-module-screens/). One example is the [Predator X27 P](https://www.tftcentral.co.uk/blog/acer-predator-x27-p-with-minor-updates-now-supporting-vrr-over-hdmi/) and [Acer-Monitor Predator XB273 X](https://www.tftcentral.co.uk/blog/acer-predator-xb273-x-with-27-240hz-ips-panel-0-1ms-g2g-and-native-g-sync/)

> NVIDIA confirmed for us that future G-sync module screens can be capable of supporting both HDMI-VRR and adaptive-sync for HDMI and DisplayPort, as the XB273 X’s specs had suggested. A firmware update is being made to the v1 and v2 G-sync hardware modules for future use which allows these new features. - Source: [TFT Central](https://www.tftcentral.co.uk/blog/nvidia-open-up-support-for-adaptive-sync-freesync-for-future-native-g-sync-module-screens/)

![1-630 7a2ac7f6](https://user-images.githubusercontent.com/727123/69557147-5bf51e80-0fa6-11ea-9fa6-d53ea4eee5f3.jpg)

## Support
Theoretically every game console with HDMI-VRR could work, as well as EVERY (_modern_) graphics card (HDMI + DisplayPort, because the Adaptive-Sync standard is based on their specifications). That said, VRR with HDMI 2.1 is required so "modern" means in this context every card which supports it.

> That means that in the future a display featuring an NVIDIA G-sync module could work with compatible games consoles for HDMI-VRR. It could also work with any graphics card based on the adaptive-sync standard over HDMI and DisplayPort. This means that you would be able to use a Native G-sync screen (with module) from an AMD graphics card for VRR! - Source: TFT Central

### Older Monitors with G-Sync modules?

Theoretical a [firmware update](https://www.acer.com/ac/zh/TW/content/predator-model/MM.THLTT.002) would be enough to introduce the support. Sadly, NV and others are blocking this.

> We confirmed with NVIDIA that it will NOT be possible to update firmware to any existing Native G-sync screen, or request updates to allow your current G-sync screen to be updated so that it would work with AMD graphics cards. The new firmware will only be applied to future G-sync module displays. - Source: [TFT Central](https://www.tftcentral.co.uk/blog/nvidia-open-up-support-for-adaptive-sync-freesync-for-future-native-g-sync-module-screens/)

In other words it's blocked via software (firmware) restrictions, and _NV screwed_ their customers yet again. They basically "force" you to buy another monitor on purpose, instead of providing firmware patches for every G-Sync Monitor (with G-Sync module). 

This is not a "rant" btw, but I criticize NVIDIA and some vendors because:
- They should work together to "patch" it for everyone which owns a G-Sync Monitor.
- They should open the source code, so that AMD and NVIDIA could solve the existent problems together to provide a middle-way for gamers as well as OEM's.
- It's hard (if not impossible) for vendors to debug/audit problems without source code, which means customers are blaming them to "not fix" the known problems, but at the end NV has to provide the information and sources.

## G-Sync still superior? 
The benefits of G-Sync are proven as ["minimal"](https://www.digitaltrends.com/computing/freesync-vs-g-sync/). However, I agree that (on AMD's side) [FreeSync Ghosting](https://www.reddit.com/r/samsung/comments/do2lyo/about_the_freesync_ghosting_problem_on_samsung/) and some performance [issue](https://www.reddit.com/r/Amd/comments/dio4m7/freesync_ghosting_on_5700xt/) are still [unresolved](https://www.reddit.com/r/nvidia/comments/ap6i5l/one_big_difference_in_nvidias_adaptive_sync/). But the current [performance benefit](https://www.reddit.com/r/Monitors/comments/d7r4jw/now_that_nvidia_cards_support_freesync_is_there_a/) is [shrinking](https://www.reddit.com/r/Monitors/comments/d7r4jw/now_that_nvidia_cards_support_freesync_is_there_a/f14oim5/). I think the biggest problems are the limiters, as explained over [here](https://www.blurbusters.com/gsync/gsync101-input-lag-tests-and-settings/).

### Why did I wrote this?
Well, I got ask if it's possible to patch this within the driver and the answer is clear - no it is not possible. I also think the information is interesting.

**Comment by ValZapod** [comment]
Question. Does VRR metadata fields in HDMI 2.1 or 2.0b through optional channels support the 1 Hz? Like G-Sync does, so called 0 Hz mode... You know that Apple watch series 4 also support... If you remeber there is also a new perfomance mode of Nvidia that stops to work on new frames if there are no differences in picture, combined with this, it can be a good thing... Also may be good for this https://youtu.be/N1BAYfzCzu4
