### ISSUE TITLE
Does this support GeForce 820m

### ISSUE THREAD

**Issue by bukyapavankumar** [CHEF-KOCH/nVidia-modded-Inf#12]
My nvidia GeForce 820m cannot install these drivers

**Comment by CHEF-KOCH** [comment]
I need more information:
* OS
* Driver version with link
* Inf version with link
* All other information which helps to resolve the problem

**Comment by bukyapavankumar** [comment]
Windows 10 1909

https://github.com/CHEF-KOCH/nVidia-modded-Inf/releases/tag/441.41

I have nvidia GeForce 820m Fermi
Latest supported driver is 391.35.
When installing modified drivers 441.11.im getting installer cannot continue error.
How do i make newer drivers compatible with my 820m GPU.

**Comment by bukyapavankumar** [comment]
Or suggest me the best modified version that supports 820m.

**Comment by CHEF-KOCH** [comment]
NVIDIA removed Fermi support from the source code. You have to use the latest Fermi driver, that's why I listed it.
