### ISSUE TITLE
1050 ti dxr support via mod?

### ISSUE THREAD

**Issue by noise2014** [CHEF-KOCH/nVidia-modded-Inf#2]
Hello sir!

will you make the 1050 ti 4gb support dxr via you modding knowledge please, because some nvidia staff said its not planned. So i guess its not impossible.

thanks sir.

**Comment by CHEF-KOCH** [comment]
They are already [listed and integrated](https://github.com/CHEF-KOCH/nVidia-modded-Inf/blob/master/Docs/Device%20ID%20List/cards.txt).
