### ISSUE TITLE
Does this work on all Geforce Series 7?

### ISSUE THREAD

**Issue by HitaloSama** [CHEF-KOCH/nVidia-modded-Inf#21]
I'm wondering if this works for Geforce Series 7, more precisely the Geforce 7200 Gs / 7300 Se (it uses driver 309.08).

**Comment by CHEF-KOCH** [comment]
[Which GPUs are supported and which are legacy?!](https://github.com/CHEF-KOCH/nVidia-modded-Inf/issues/7)
