### ISSUE TITLE
 I have a doubt

### ISSUE THREAD

**Issue by Superhackman** [CHEF-KOCH/nVidia-modded-Inf#24]
What does it offer and what is the advantage of installing modded nvidia inf desktop vs the original inf, gives better performance? or add something new?
and this modded nvidia inf for desktop works on any nvidia graphics card? I'm just talking about desktop graphics cards, just desktop
my graphic card is MSI GTX 1050ti Gaming X 4GB Dual Fan

**Comment by CHEF-KOCH** [comment]
Thanks for ignoring the entire Readme.md which explains in details that the modded inf is to support cards who are not supported by the driver (not more and not less).
