### ISSUE TITLE
Nvidia Control Panel only shows developer settings. No 3D settings

### ISSUE THREAD

**Issue by saftle** [CHEF-KOCH/nVidia-modded-Inf#26]
**I'm submitting a ...**
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
```

**Current behavior**
The nvidia control panel is completely blank aside from developer settings. See here: 
![image](https://user-images.githubusercontent.com/852777/85957030-1b211600-b98a-11ea-9649-0695b20a24d1.png)

**Expected or/and desired behavior**
The usual settings should be available as well

**Minimal reproduction of the problem with instructions**
Occurred directly after installing. Prior to installing, the control panel had all of the options (aside from the developer option, this is new)

**What is the motivation / use case for changing the behavior?**
Self-explanatory

**Environment**
* **Driver version:** nVidia GeForce 451.48 GRD + NSD RePack
NVIDIA.451.48.Desktop.Standard.exe

* **OS:**

- [ ] Windows 7 Build:
- [ ] Windows 8 Build:
- [ ] Windows 8.1 Build:
- [X] Windows 10 Build:  18363.900

* **Others:**
N/A

**Comment by CHEF-KOCH** [comment]
You can still use nVidia Inspector for such cases (just for reference).
I uploaded new packages, however I'm not going to upload new NSD/Notebook versions (or not anytime soon).
