### ISSUE TITLE
430.35 vs 430.39

### ISSUE THREAD

**Issue by kurtextrem** [CHEF-KOCH/nVidia-modded-Inf#4]
Any ideas what the huge branch difference could be? 

And, 430.35 is 535 MB while 430.39 is 386 MB. That's a huge difference. What the hell takes 150 MB?

**Comment by CHEF-KOCH** [comment]
You can compress the 430.35 driver at the same size. .35 was _ripped_ from the Windows Update Server and is basically only a dump to collect the driver. This explains the compression difference. I did not touched the driver or re-compressed it (but I could).

The versions number is totally irrelevant people have to look at the branch, the branch you compare here are different: 421_76-9 vs. 430_34-5. How a branch is to _read_ is already explained right under the `Driver Branch` document.
