### ISSUE TITLE
dxr support for gtx 1050ti 4g

### ISSUE THREAD

**Issue by darksiders2** [CHEF-KOCH/nVidia-modded-Inf#6]
is modding a driver for dxr support in gtx 1050 ti 
that hard
i mean nvidia already has driver with dxr for pascal series .they just skipped 1050ti.
is it at the .inf level or .dll

**Comment by donizettilorenzo** [comment]
Up! Please give us a clear answer!

**Comment by CHEF-KOCH** [comment]
It's .dll, so the answer is no - not from my side, I'm sorry.
